# $schema: https://json.schemastore.org/github-workflow.json

name: Release

on:
  workflow_call:
    inputs:
      apko-config-file:
        description: "The apko config file to build"
        type: string
        default: "apko.yaml"
      apko-lock-file:
        description: "The apko lock file to use"
        type: string
        default: "apko.lock.json"
      image-name:
        description: "The name of the built image"
        type: string
        default: ${{ github.repository }}
      image-tag:
        description: "The tag of the built image"
        type: string
        default: "latest"

permissions: {}

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build

    uses: ./.github/workflows/build.yaml
    with:
      apko-config-file: ${{ inputs.apko-config-file }}
      apko-lock-file: ${{ inputs.apko-lock-file }}
      image-name: ${{ inputs.image-name }}
      image-tag: ${{ inputs.image-tag }}

    permissions:
      contents: read  # to read the source needed to build the image

  push-images:
    name: Push container images to registry

    needs:
      - build

    runs-on: ubuntu-24.04

    permissions:
      packages: write  # to push the built image to the registry

    steps:
      - name: Setup `crane`
        uses: imjasonh/setup-crane@feee3b6bb0d4c68370f256a4502498c9227e5c6b # v0.7

      - name: Download OCI images
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: build-oci-images
          path: dist/oci-images

      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images
        shell: bash
        env:
          IMAGE_NAME: ${{ inputs.image-name }}
          IMAGE_TAG: ${{ inputs.image-tag }}
        run: crane push --index dist/oci-images "${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"

  attest-provenance:
    name: Attest build provenance

    needs:
      - build
      - push-images

    permissions:
      id-token: write           # to get ID needed to sign attestation
      packages: write           # to store attestation
      attestations: write       # to store attestation
      artifact-metadata: write  # to store attestation

    strategy:
      fail-fast: false
      matrix:
        digests: ${{ fromJson(needs.build.outputs.digests) }}

    runs-on: ubuntu-24.04

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Attest Provenance (${{ matrix.digests.arch }})
        uses: actions/attest@1e69f48acb82d1966a394da916b4c1698aa569d6 # v4.2.2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ inputs.image-name }}
          subject-digest: ${{ matrix.digests.digest }}
          push-to-registry: true

  attest-sbom:
    name: Attest SBOM

    needs:
      - build
      - push-images

    permissions:
      id-token: write           # to get ID needed to sign attestation
      packages: write           # to store attestation
      attestations: write       # to store attestation
      artifact-metadata: write  # to store attestation

    strategy:
      fail-fast: false
      matrix:
        digests: ${{ fromJson(needs.build.outputs.digests) }}

    runs-on: ubuntu-24.04

    steps:
      - name: Download SBOMs
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: build-sboms
          path: dist/sboms

      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Attest SBOM (${{ matrix.digests.arch }})
        uses: actions/attest@1e69f48acb82d1966a394da916b4c1698aa569d6 # v4.2.2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ inputs.image-name }}
          subject-digest: ${{ matrix.digests.digest }}
          sbom-path: dist/sboms/sbom-${{ matrix.digests.arch }}.spdx.json
          push-to-registry: true
